### PR TITLE
General code cleanup and replaces

### PR DESCRIPTION
**Pull request by double-beep**
Replace "set /p" with "choice /c". After review merging...

### CODE REVIEW

**Comment by double-beep** [comment]
And releasing to 1.2. Closing for now.

**Comment by helper-beep** [comment]
Merge.

**Comment by double-beep** [comment]
Duplicate of #53.

**Comment by double-beep** [comment]
`snake_game.bat:101`
diff --git a/all_about folders.bat b/all_about folders.ba

**Pull request closed without merging**
