### PR TITLE
Update expert folder file

### PR DESCRIPTION
**Pull request by double-beep**
This update adds "choice /c" command and %errorlevel%. Will add description with "::" soon.
Testing that, closing.

### CODE REVIEW

**Comment by helper-beep** [comment]
Tested, ok and approving after reopen.

**Comment by helper-beep** [comment]
Awaiting YOUR merge, closing again.

**Comment by double-beep** [comment]
Ok, I found another possible update. I will look into it.

**Comment by helper-beep** [comment]
Approved, excellent!

**Pull request closed without merging**
